### ISSUE TITLE
Compatibility issue with peakrdl-python

### ISSUE THREAD

**Issue by MarinaQT** [SystemRDL/PeakRDL#26]
Hello dear all
today tried the plugin peakrdl-python, which unfortunately is not working on my side.
But then all of a sudden the basic commands of peakrdl like peakrdl uvm were no longer working...

Then erased the package peakrdl-python, and they work again. 
So it seems a compatibility problem...
Any experience/tips on that?

OBS.:
1) The other plugin available peakrdl-halcpp worked very smoothly, had no compatibility problems there.

2) the error message after had installed peakrdl-python was:
Traceback (most recent call last):
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/bin/peakrdl", line 8, in <module>
    sys.exit(main())
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl/main.py", line 109, in main
    subcommands += get_exporter_plugins(cfg)
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl/plugins/exporter.py", line 44, in get_exporter_plugins
    cls = ep.load()
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl_python/__init__.py", line 4, in <module>
    from .exporter import PythonExporter
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl_python/exporter.py", line 29, in <module>
    from .lib import get_array_typecode
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl_python/lib/__init__.py", line 14, in <module>
    from .base import AddressMap
  File "/home/mdqe/PycharmProjects/pythonProject_rm_blocks/venv/lib/python3.6/site-packages/peakrdl_python/lib/base.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by amykyta3** [comment]
PeakRDL-Python is a community plug-in that I do not maintain. Please open a ticket in the appropriate place: https://github.com/krcb197/PeakRDL-python/issues

@krcb197 - It looks like your `setup.py` is missing a Python version specifier. Recommend adding this to denote that it does not support Python3.6 or older:
```python
python_requires='>=3.7',
```

@MarinaQT what seems to be happening is the `annotations` future feature is not available in py3.6 and older, and since PeakRDL-python does not advertise that it does not support py3.6, it falsely tries to install it anyways.
