### ISSUE TITLE
Installation problems in Shell (pip install) vs. PyCharm

### ISSUE THREAD

**Issue by MarinaQT** [SystemRDL/PeakRDL#28]
Hello Alex

As mentioned before (see  https://github.com/SystemRDL/PeakRDL/issues/25 ) , i get peakrdl installed and running within PyCharm, but can not install properly directly on shell (with pip install). 
It seems to be a compatibility problem as the installation goes through, but afterwards peakrdl commands are not recognised. 
Error messages when typing any peakrdl commands in shell after installation are:

```
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/tomli-2.0.1-py3.6.egg/tomli/_parser.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Thinking about compatibility issues, went on checking  for installation status, and changed package versions in shell to match PyCharm versions. Error message changed, but still persists. Full error message, and pip list below. 
Can you give further hints how to debug this?
Thanks for help & attention

```
==================================
ERROR MESSAGE after same packages
==================================
Traceback (most recent call last):
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/bin/peakrdl", line 33, in <module>
    sys.exit(load_entry_point('peakrdl==0.8.0', 'console_scripts', 'peakrdl')())
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/peakrdl-0.8.0-py3.6.egg/peakrdl/main.py", line 109, in main
    subcommands += get_exporter_plugins(cfg)
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/peakrdl-0.8.0-py3.6.egg/peakrdl/plugins/exporter.py", line 44, in get_exporter_plugins
    cls = ep.load()
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/peakrdl_html-2.10.1-py3.6.egg/peakrdl_html/__init__.py", line 1, in <module>
    from .exporter import HTMLExporter
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/peakrdl_html-2.10.1-py3.6.egg/peakrdl_html/exporter.py", line 14, in <module>
    from gitmetheurl import GitMeTheURL
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/git_me_the_url-2.1.0-py3.6.egg/gitmetheurl/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/git_me_the_url-2.1.0-py3.6.egg/gitmetheurl/base.py", line 5, in <module>
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/GitPython-3.1.31-py3.6.egg/git/__init__.py", line 44, in <module>
    from git.objects import *  # @NoMove @IgnorePep8
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/GitPython-3.1.31-py3.6.egg/git/objects/__init__.py", line 9, in <module>
    from .commit import *
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/GitPython-3.1.31-py3.6.egg/git/objects/commit.py", line 11, in <module>
    from git.diff import Diffable
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/GitPython-3.1.31-py3.6.egg/git/diff.py", line 8, in <module>
    from git.cmd import handle_process_output
  File "/home/mdqe/PycharmProjects/pythonProject_shell/venv_peakrdl/lib64/python3.6/site-packages/GitPython-3.1.31-py3.6.egg/git/cmd.py", line 6
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```
```
==================================
PIP LIST
==================================
Package                Version
---------------------- -------
antlr4-python3-runtime 4.11.1
colorama               0.4.6
git-me-the-url         2.1.0
gitdb                  4.0.10
GitPython              3.1.31
importlib-metadata     4.8.3
Jinja2                 3.1.2
Markdown               3.4.3
MarkupSafe             2.1.3
peakrdl                0.8.0
peakrdl-html           2.10.1
peakrdl-ipxact         3.4.1
peakrdl-regblock       0.15.0
peakrdl-systemrdl      0.3.0
peakrdl-uvm            2.3.0
pip                    21.3.1
python-markdown-math   0.8
setuptools             59.6.0
smmap                  5.0.0
systemrdl-compiler     1.26.0
tomli                  1.2.3
typing_extensions      4.1.1
wheel                  0.37.1
zipp                   3.6.0
```

**Comment by amykyta3** [comment]
This is definitely not a PeakRDL issue.
It looks like what is happening is that you are installing packages that are incompatible with Python3.6.

For example, `tomli` [dropped support for Python3.6 in v2.00](https://github.com/hukkin/tomli/blob/master/CHANGELOG.md#200), yet you still have somehow managed to force it to install an incompatible version (2.0.1) despite it [advertising it is not compatible](https://github.com/hukkin/tomli/blob/master/pyproject.toml#L13).

Same situation happened in your other example with `GitPython`.

I would recommend starting from a fresh venv. Do not force-install specific versions of dependencies and allow pip to properly install the correct one.

**Comment by MarinaQT** [comment]
Hello Alex

thanks for the hint! 
Yes, apparently it was GitPython. Took an older version (3.1.18), restarted peakrdl installation and now working! 
I was not exactly forcing any specific packages, i just inherited an status within our Linux environment. But will now clarify and clean up. 
Sorry for the time investment on your side. Best regards!

**Comment by amykyta3** [comment]
Great! Glad you were able to figure out the issue.
