### ISSUE TITLE
[BUG] Still seeing importlib.metadata issues.

### ISSUE THREAD

**Issue by shareefj** [SystemRDL/PeakRDL#39]
**Describe the bug**
See #16 for the background.

In order to replicate, run the following to perform an editable installation of peakrdl-regblock:

```
$ mkdir testcase
$ cd testcase/
$ python3.10 -m venv venv
$ . venv/bin/activate
$ pip install peakrdl
$ to ../PeakRDL-regblock
$ pip install -e .
$ peakrdl help
Traceback (most recent call last):
  File "/home/shareefj/git/testcase/venv/bin/peakrdl", line 8, in <module>
    sys.exit(main())
  File "/home/shareefj/git/testcase/venv/lib/python3.10/site-packages/peakrdl/main.py", line 135, in main
    raise RuntimeError(f"More than one exporter plugin was registered with the same name '{sc.name}': \n\t{sc_dict[sc.name]}\n\t{sc}")
RuntimeError: More than one exporter plugin was registered with the same name 'regblock':
        <peakrdl_regblock.__peakrdl__.Exporter object at 0x7fe3f0835390>
        <peakrdl_regblock.__peakrdl__.Exporter object at 0x7fe3f0339bd0>
```

**Comment by amykyta3** [comment]
In this particular case, this is expected.
The `peakrdl` package implicitly installs the `peakrdl-regblock` plugin. If you install it prior to installing the editable version, it should work.
