### ISSUE TITLE
Support for  dictionary in the peakrdl.toml

### ISSUE THREAD

**Issue by krcb197** [SystemRDL/PeakRDL#42]
peakrdl-python uses Jinja templates for the generation of Python wrappers. The PythonExporter can allow the user to provide their own templates and context. The main use case for this would be overriding the docstring with internal header on files.

I want to have two new keys in the peakrdl header:

- A directory path to the folder of user-provided templates
- A structure that the user can populate based on the needs of their template

There is an open pull request where I have been trying to implement this feature, see krcb197/PeakRDL-python#149 however, I have been struggling to set up the schema as needed

For example the following toml is part of the test cases in the pull request:
``` toml
[python]
user_template_dir = "tests/alternative_templates_dynamic"
user_template_context = { extra_param_1 = 'Bill', extra_param_2 = 'Johny'}
```

However, the data structure of  `user_template_context `  will be dependent on the user's template, therefore the scheme is that it is a dictionary of anything. Having studied the documentation, I expected the system of the schema to be as follows:

``` python 
    from peakrdl.config import schema 
    cfg_schema = {
        "user_template_dir": schema.DirectoryPath(),
        "user_template_context": { "*": schema.AnyType }
    }
```

When I use this schema with peakrdl the following error occurs:
```
(venv_311) <home>\PeakRDL-python>peakrdl python tests/testcases/basic.rdl -o peakrdl_out/simple_user_template/ --peakrdl-cfg tests/alternative_templates_toml/peakrdl.toml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<home>\PeakRDL-python\venv_311\Scripts\peakrdl.exe\__main__.py", line 7, in <module>
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\main.py", line 129, in main
    subcommand._load_cfg(cfg)
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\subcommand.py", line 43, in _load_cfg
    self.cfg = cfg.get_namepsace(self.name, schema.normalize(self.cfg_schema))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\config\schema.py", line 176, in normalize
    return FixedMapping(raw_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\config\schema.py", line 109, in __init__
    self.schema[k] = normalize(v)
                     ^^^^^^^^^^^^
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\config\schema.py", line 173, in normalize
    return UserMapping(raw_schema['*'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\config\schema.py", line 140, in __init__
    self.value_schema = normalize(raw_value_schema)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<home>\peakrdl-python\venv_311\Lib\site-packages\peakrdl\config\schema.py", line 179, in normalize
    raise RuntimeError(f"Invalid schema object: {repr(raw_schema)}")
RuntimeError: Invalid schema object: <class 'peakrdl.config.schema.AnyType'>
```

Can you offer any insights how to setup the schema correctly?

**Comment by krcb197** [comment]
Found the error after studying the unit tests carefully. The correct schema is:
``` python
    from peakrdl.config import schema 
    cfg_schema = {
        "user_template_dir": schema.DirectoryPath(),
        "user_template_context": { "*": schema.AnyType() }
    }
```
